### ISSUE TITLE
code review 20220403

### ISSUE THREAD

**Issue by elsie-h** [opensafely/booster-effectiveness-autumn-2022#1]
This repo implements analyses of the comparative (pfizer vs moderna) and relative (boosted vs unboosted) effectiveness of the autumn 2022 booster vaccines.

@wjchulme - could you please provide a code review? Most of the code is taken from repos that implement comparative OR relative analyses, but there are some changes to accommodate doing both at once. 

For now, the analysis is restricted to 2 matching rounds, 2 outcomes, no subgroups, and three postbaseline cuts.

Actions are included for data processing, matching, table 1, and km and Cox models.

I've tried to minimise the number of large patient-level datasets being stored, so the [process_postmatch](https://github.com/opensafely/booster-effectiveness-autumn-2022/blob/main/analysis/process/process_postmatch.R) is called from several other scripts.

**Comment by wjchulme** [comment]
Looks good! I've checked that everything runs. I've looked through the code and everything makes sense, though I might be over-familiar. 

For the comparative models, the treatment variable is still called `treated` (taking values `0`/`1`), which is fine but might be slightly confusing for released outputs. 

I made some very minor changes as I was going along in #2 but these barely merit a second glance. Feel free to look and merge when you're happy.
